version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: gz_raw_sales
        description: sales of Greenweez
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key
          - name: pdt_id
            description: foregin key to product
          - name: revenue
            description: the amount paid by the costomer
          - name: quantity
            description: the quantity of products
        tests:
          - unique:
              column_name: "(orders_id||'_'||pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: product_id
            description: primary key of the product
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweea
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: Information about adwords platform
      - name: bing
        identifier: raw_gz_bing
        description: Information about bing platform
      - name: criteo
        identifier: raw_gz_criteo
        description: Information about criteo platform
      - name: facebook
        identifier: raw_gz_facebook
        description: Information about facebook platform