sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: Information about adwords platform
      - name: bing
        identifier: raw_gz_bing
        description: Information about bing platform
      - name: criteo
        identifier: raw_gz_criteo
        description: Information about criteo platform
      - name: facebook
        identifier: raw_gz_facebook
        description: Information about facebook platform
